### ISSUE TITLE
Missing filter

### ISSUE THREAD

**Issue by pisten** [bkielczewski/example-dropwizard-guice#1]
New to programming (and therefor Maven and Java as well) I enjoy your help!

But some things needed to be fixed:
1. groupId should remove dropwizard (in groupId and mainClass)
1. I needed to add a filter to the POM:
                               <filter>
                                   <artifact>_:_</artifact>
                                   <excludes>
                                       <exclude>META-INF/_.SF</exclude>
                                       <exclude>META-INF/_.DSA</exclude>
                                       <exclude>META-INF/*.RSA</exclude>
                                   </excludes>
                               </filter>

**Comment by bkielczewski** [comment]
Great, thank you. I completely forgot to update shade plugin config. Hopefully fixed now.
